### ISSUE TITLE
First section: plots

### ISSUE THREAD

**Issue by Lucacalderaro** [trotter-suzuki-mpi/notebooks#1]
The function `two_vortices` returns the precession frequency over the rabi coupling. We want to plot this quantity vs `lOmega_over_r12`.

The easiest way may be to create a DataFrame with three columns called 'l_omega_r12', 'length_x' and 'omega_rot/omega'. Each row of the DataFrame should correspond to a simulation, being:
'l_omega_r12' the value of `lOmega_over_r12`, 'length_x' two times the value of `radius` and 'omega_rot/omega' the returned value from `two_vortices`.

Being df the name of the DataFrame, the following cells should correctly works and plot the two figures 1a and 1b of the manuscript.

**Comment by peterwittek** [comment]
This was completed by 35cc70b6267daa88da88a2f26840ece73a633e3e.
